services:
  astro-blog:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    image: astro:latest
    pull_policy: build
    container_name: astro-local-blog
    ports:
      - 4321:80
    restart: unless-stopped
networks: {}
